server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ccgogoing/spring-cloud-config-repo
          username: pekxxoo@163.com
          password: lc@19940518?

logging:
  level:
    org.springframework.cloud: debug
    org.springframework.boot: debug