server:
  port: 8050
eureka:
  client:
    service-url:
      defaultZone: http://user:ccgogoing@localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-file-upload
  http:
    multipart:
      max-file-size: 2000MB  # Max file size д╛хо1M
      max-request-size: 2500MB  # Max request size д╛хо10M
